repos:
  - repo: https://codeberg.org/frnmst/md-toc
    rev: '8.1.4'
    hooks:
    - id: md-toc
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: no-commit-to-branch
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.0
    hooks:
    - id: markdownlint
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    - id: detect-secrets
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.0
    hooks:
      - id: gitleaks
